"""Pydantic schemas for the Patterm MVP API."""
from datetime import datetime, date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field


class Specialty(str, Enum):
    """Medical specialties supported by the MVP."""

    cardiology = "cardiology"
    dermatology = "dermatology"
    general_practice = "general_practice"
    orthopedics = "orthopedics"
    pediatrics = "pediatrics"


class Clinic(BaseModel):
    """Public clinic information exposed to patients."""

    id: str = Field(..., description="Stable identifier of the clinic")
    name: str
    specialty: Specialty
    city: str
    street: str
    postal_code: str
    contact_email: EmailStr


class ClinicCreate(BaseModel):
    """Payload for creating a new clinic. The identifier is generated by the system."""

    name: str
    specialty: Specialty
    city: str
    street: str
    postal_code: str
    contact_email: EmailStr


class SlotStatus(str, Enum):
    """Lifecycle status of appointment slots."""

    open = "open"
    booked = "booked"
    cancelled = "cancelled"


class AppointmentSlot(BaseModel):
    """A bookable appointment slot."""

    id: str
    clinic_id: str
    start: datetime
    end: datetime
    is_virtual: bool = Field(
        False,
        description="Whether the appointment takes place virtually (telemedicine)",
    )
    status: SlotStatus = Field(default=SlotStatus.open, description="Lifecycle status of the slot")
    booked_patient_id: Optional[str] = Field(
        default=None, description="Identifier of the patient who booked the slot"
    )
    patient_snapshot: Optional["PatientProfile"] = Field(
        default=None,
        description=(
            "Patient profile snapshot shared with the treating clinic when the slot is "
            "booked, based on explicit consent."
        ),
    )


class PatientProfile(BaseModel):
    """Minimal patient profile stored in the encrypted data store."""

    id: str
    email: EmailStr
    first_name: str
    last_name: str
    date_of_birth: date


class TreatmentNote(BaseModel):
    """Versioned treatment note written by medical staff."""

    version: int
    author: str
    created_at: datetime
    summary: str
    next_steps: Optional[str] = None


class PatientRecord(BaseModel):
    """Complete patient record stored per patient."""

    profile: PatientProfile
    appointments: List[AppointmentSlot] = Field(default_factory=list)
    treatment_notes: List[TreatmentNote] = Field(default_factory=list)
    consents: List[str] = Field(
        default_factory=list,
        description="Identifiers of clinics that currently have access to the record.",
    )


class AppointmentRequest(BaseModel):
    """Incoming booking request."""

    slot_id: str


class AppointmentConfirmation(BaseModel):
    """Response that confirms the booking."""

    appointment: AppointmentSlot
    clinic: Clinic
    confirmation_number: str


class TreatmentNoteRequest(BaseModel):
    """New treatment note payload."""

    author: str
    summary: str
    next_steps: Optional[str] = None


class ConsentRequest(BaseModel):
    """Request to share a patient record with another clinic."""

    requester_clinic_id: str
    grant: bool = Field(
        True,
        description="Whether the patient approves (True) or revokes (False) the consent.",
    )


class ShareStatus(BaseModel):
    """Current consent status for a given clinic."""

    clinic_id: str
    granted: bool
    updated_at: datetime


class AuditEvent(BaseModel):
    """Structured audit trail event."""

    id: str
    actor: str
    action: str
    patient_id: Optional[str]
    timestamp: datetime
    payload_hash: str


class UserRole(str, Enum):
    """Supported roles for fine-grained authorization."""

    patient = "patient"
    clinic_admin = "clinic_admin"
    provider = "provider"
    platform_admin = "platform_admin"


class UserPublicProfile(BaseModel):
    """Public representation of an authenticated user."""

    id: str
    email: EmailStr
    role: UserRole
    display_name: str
    clinic_id: Optional[str] = None


class LoginRequest(BaseModel):
    """Credentials for issuing an authentication token."""

    email: EmailStr
    password: str


class AuthToken(BaseModel):
    """Returned session token and accompanying profile."""

    token: str
    user: UserPublicProfile


class PatientRegistration(BaseModel):
    """Payload to create a new patient account. The identifier is generated by the platform."""

    email: EmailStr
    password: str
    first_name: str
    last_name: str
    date_of_birth: date


class ClinicRegistration(BaseModel):
    """Administrative payload to onboard a new clinic and its lead user."""

    clinic: ClinicCreate
    admin_email: EmailStr
    admin_password: str
    admin_display_name: str


class ClinicRegistrationResponse(BaseModel):
    """Response payload when onboarding a new clinic."""

    clinic: Clinic
    admin: UserPublicProfile


class ProviderRegistration(BaseModel):
    """Registration payload for a clinician tied to a clinic."""

    clinic_id: str
    email: EmailStr
    password: str
    display_name: str
    specialty: Specialty


class SlotCreationRequest(BaseModel):
    """Payload for clinics to create new appointment slots."""

    start: datetime
    end: datetime
    is_virtual: bool = False


class SlotUpdateRequest(BaseModel):
    """Payload for updating slot metadata."""

    start: Optional[datetime] = None
    end: Optional[datetime] = None
    is_virtual: Optional[bool] = None


class RescheduleRequest(BaseModel):
    """Patient-initiated reschedule payload."""

    new_slot_id: str


class ClinicBooking(BaseModel):
    """Booking information surfaced to clinics with patient consent."""

    slot: AppointmentSlot
    patient: Optional[PatientProfile]


class ProviderProfile(BaseModel):
    """Profile data returned for clinicians within a clinic."""

    id: str
    display_name: str
    email: EmailStr
    specialty: Specialty
